apiVersion: v1
kind: Service
metadata:
  name: redis-primary
  namespace: {{namespace}}
  labels:
    app: redis-primary
spec:
  ports:
    - port: 6379
      targetPort: 6379
  type: ClusterIP
  selector:
    app: redis-primary
