apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-secondary
  namespace: {{namespace}}
spec:
  selector:
    matchLabels:
      app: redis-secondary
  replicas: {{secondary_replicas}}
  template:
    metadata:
      labels:
        app: redis-secondary
    spec:
      containers:
        - name: secondary
          image: docker.io/bitnami/redis:6.2
          resources:
            requests:
              cpu: 100m
              memory: 100Mi
          env:
            - name: REDIS_REPLICATION_MODE
              value: "slave"
            - name: REDIS_MASTER_HOST
              value: "redis-primary"
            - name: REDIS_MASTER_PORT_NUMBER
              value: "6379"
            - name: REDIS_MASTER_PASSWORD
              value: "{{master_password}}"
            - name: REDIS_PASSWORD
              value: "{{password}}"
            - name: REDIS_DISABLE_COMMANDS
              value: "{{disabled_commands}}"
          ports:
            - containerPort: 6379
