apiVersion: v1
kind: Service
metadata:
  name: redis-secondary
  namespace: {{namespace}}
  labels:
    app: redis-secondary
spec:
  ports:
    - port: 6379
  type: ClusterIP
  selector:
    app: redis-secondary
